### ISSUE TITLE
margins - still need fine tuning

### ISSUE THREAD

**Issue by fivefishstudios** [Cameron-Burkholder/rose-framework#2]
The latest master branch is much better. Previously the last div was wrapping around the next line. 

But I think the .unit margin values still needs fine-tuning. The last div .unit still isn't flushed to the right border of the parent div element. 

https://image.ibb.co/huuyf5/border_rose.png

**Comment by Cameron-Burkholder** [comment]
Thank you for bringing it up. I did notice it, and I'm working on it, but my SCSS compiler is being a little weird. I'll do my best to handle it by the end of the day.

**Comment by fivefishstudios** [comment]
Hey, no rush. I was also trying to fix that same issue on the 0.1 version, but then noticed you made new commits so I re-downloaded your repository.  I see you got it fixed, just that little bitty thing remaining.

**Comment by Cameron-Burkholder** [comment]
Now, I don't know how widely it's supported, and I don't have really any experience with it, but do you think it would be worth it to redo the grid with CSS Grid while I'm already reformatting the margin?

**Comment by fivefishstudios** [comment]
What exactly do you mean by CSS Grid? Like a 960 Grid System?

**Comment by Cameron-Burkholder** [comment]
Well, there is a new built in CSS Grid layout system that started rolling out in March I think. If you Google it you can see the MDN page and CSS tricks review of it too

**Comment by fivefishstudios** [comment]
Oh I see... interesting. Never heard of it until now. No comment at the moment, as I haven't used it or even played with it.

**Comment by Cameron-Burkholder** [comment]
I've heard of it, but I've never used it. I'm gonna play around with it, and possible flex box too, and see what might work best.

**Comment by Cameron-Burkholder** [comment]
So I've been doing some experimentation with CSS Grid, and here is a little CodePen laying out how it might work. We may not be able to support offsetting because there is no way I can imagine doing that, however, it would make the grid much much much easier. I mean, already look at how fewer lines of code are used for this simple grid.

https://codepen.io/CameronBurkholder/pen/XgpebO

**Comment by fivefishstudios** [comment]
That looks so much more simpler... this new grid seems to have potential.

re: offsetting. Check this out!  Even just an empty <div> causes the layout to offset by 1 unit each time. Maybe this is a clue and somehow we can make this into a class or something. 

<div class="grid-full-8">
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>   
  <div class="unit md-1-8"></div>
</div>

**Comment by fivefishstudios** [comment]
Holy cow... this is so much easier. There is already a built in offset!  check this out
```
.md-offset-1-8{
  grid-column-start: 2;
}
```

```
<div class="grid-full-8">
  <div class="md-offset-1-8">I'M HERE</div>
  <div class="unit md-1-8"></div>
</div>
```

**Comment by Cameron-Burkholder** [comment]
Yeah that would be great. Originally I saw that you could do that, but it gets messy if you have multiple elements or multiple offsets. But, if we go with the column start class identification, we could forgo the "offset" entirely.

**Comment by fivefishstudios** [comment]
the column-start seems to be 0-based, and starts it's origin from the start of the same line (and not from end of the last div). 

```
<div class="grid-full-8">
  <div class="unit start-2">I'M HERE</div>
  <div class="unit md-1-8"></div>
  <div class="unit start-6">OVER HERE</div>
</div>
```
```
.start-2{
  grid-column-start: 2;
}

.start-6{
  grid-column-start: 6;
}
```

**Comment by Cameron-Burkholder** [comment]
Sorry for the absence, I've been away for the past week on vacation. I went ahead and added support for the new CSS Grid based layout. Basically, you declare the grid with .grid-[grid-size]-[margin/no-margin]. So, for a 12 base grid with no margin, do .grid-12-flat. For a 3 base grid with margin, do .grid-3. Inside, elements will automatically take up 1fr of the grid, but the elements can be set to take up a number of columns by using the screen size, then the -col- keyword, then the number of columns to span. So .md-col-3 to span 3 columns on medium. The only thing I haven't done is add the start classes, but the current documentation is mostly up to date in terms of layout, I just need to update the actual words of the documentation.
